# Generated by Django 3.0.7 on 2020-07-03 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kibana_frame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('link', models.TextField(max_length=5000)),
                ('description', models.TextField(blank=True, max_length=5000)),
                ('height', models.PositiveIntegerField(default=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Parent_frame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('nom', models.TextField(max_length=5000)),
                ('description', models.TextField(blank=True, max_length=5000)),
                ('kibanas_frame', models.ManyToManyField(to='presentation.Kibana_frame')),
            ],
        ),
        migrations.CreateModel(
            name='Parent_kibana_frame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('Kibana_frame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='presentation.Kibana_frame')),
                ('Parent_frame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='presentation.Parent_frame')),
            ],
        ),
    ]
