# Generated by Django 3.0.7 on 2020-07-03 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent_frame',
            name='kibanas_frame',
        ),
        migrations.AddField(
            model_name='kibana_frame',
            name='parents_frame',
            field=models.ManyToManyField(to='presentation.Parent_frame'),
        ),
    ]
