# Generated by Django 3.0.7 on 2020-07-03 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentation', '0003_auto_20200703_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='kibana_frame',
            name='nom',
            field=models.CharField(default='None', max_length=200),
        ),
    ]
