# Generated by Django 3.0.7 on 2020-06-13 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentation', '0004_auto_20200613_0217'),
    ]

    operations = [
        migrations.AddField(
            model_name='kibana_frame',
            name='description',
            field=models.TextField(blank=True, max_length=5000),
        ),
        migrations.AddField(
            model_name='kibana_frame',
            name='link',
            field=models.TextField(blank=True, max_length=5000),
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
