# Generated by Django 3.0.7 on 2020-06-17 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentation', '0005_auto_20200613_0304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kibana_frame',
            name='description',
            field=models.CharField(max_length=50),
        ),
    ]
