# Generated by Django 3.0.7 on 2020-06-17 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentation', '0006_auto_20200618_0114'),
    ]

    operations = [
        migrations.AddField(
            model_name='kibana_frame',
            name='height',
            field=models.CharField(default=1000, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kibana_frame',
            name='description',
            field=models.TextField(blank=True, max_length=5000),
        ),
    ]
