# Generated by Django 3.0.7 on 2020-06-18 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentation', '0007_auto_20200618_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kibana_frame',
            name='code',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='kibana_frame',
            name='height',
            field=models.PositiveIntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='kibana_frame',
            name='link',
            field=models.TextField(max_length=5000),
        ),
    ]
